
[General]
;samples_num0=037
samples_num=109
# 设置基础样本，playdoh_gen018原始.py生成数据文件名，
[gen_Paths]
input_root = M:\m\pycharm_project\project1\Data\Real\Playdoh0-3\基多类生1类-留1后置中心
;文件playdoh_gen_变1类置中心再生成
;input_root = M:\m\pycharm_project\project1\Data\Real\Playdoh0-3\Playdoh基0置中心
;input_root = M:\m\pycharm_project\project1\Data\Real\Playdoh0-3\Playdoh基1类置中心

input_root0 = M:\m\pycharm_project\project1\Data\Real\Playdoh0-3\Playdoh1
;input_root = M:\m\pycharm_project\project1\Data\Real\Playdoh0-3\Playdoh4



[Paths]
;input_root = M:\m\pycharm_project\project1\Data\Real\Playdoh0-3\Playdoh0-3_Origin
input_root = M:\m\pycharm_project\project1\Data\Real\Playdoh0-3\异常体积文件

#Playdoh0-3_gen的输入文件夹
output_root = M:\m\pycharm_project\project1\Data\Real\Playdoh0-3\Playdoh0-3_异常体积文件segm
#output_root是playdoh_segm文件。

out_folder0  = M:\m\pycharm_project\project1\Data\Real\Playdoh0-3\Playdoh0-3_gen
#Playdoh0-3_gen运行输出文件夹;out_folder = M:\m\pycharm_project\project1\Data\Real\Playdoh0-3\Playdoh0-3_gen\Playdoh0-3_gen002
out_folder1 = M:\m\pycharm_project\project1\Data\Real\Playdoh0-3\Playdoh0-3_segm
#out_folder1是playdoh_noisy文件。



[Simulation]
num_angles = 72
augmentation_samples = 90
energy_bins = 1
energy_model = mono
noise = True
save_noiseless = True

[Materials]
material_count = 2
name_1 = Playdoh
lac_1 = 0.037        
curve_1 = -
name_2 = Stone
lac_2 = 0.073
curve_2 = -

[Noise]
Flatfield = 6400.
Poisson_scaling = 1.17
Gaussian_std = 20.
Blur_width = 0.
