[General]
test_file1 = gen_train000_resnet50_r25
#新策略
test_file2 = gen_train000_resnet50_r25
#原策略

test_checkpoint_num=200
test_file3 = gen_train095_resnet50_r95010
#指定的检查点

data_root = M:/pycharm_project/project1/Data/Real/Playdoh0-3/gen_train
max_epochs = 500
patience = 25
select_weight = 0.5

# if curr_score <= best_window_score and avg_val_loss < c and average_diff < d:
;0.11 avg_val_loss = np.mean(curr_window_val)
;average_diff = np.mean(np.abs(np.array(curr_window_train) - np.array(curr_window_val))).
recent_avg_val_max  = 0.5

early_stop_ratio = 0.8
min_improvement_threshold = 0.0004
# 25epochs早停：只要小于1%/25=0.0004就是未改进，且其中的2次改进值不能大于10%/25=0.004才认可
max_improvement_threshold = 0.004
# 25epochs早停：只要小于0.5%/25=0.0004就是未改进，且其中的2次改进值不能大于10%/25=0.004才认可

batch_size = 4
use_deterministic = False



[playdoh]
c_in = 1
c_out = 3
classification_function = playdoh_triple_classification
test_folder = M:/pycharm_project/project1/Data/Real/Playdoh0-3
img_per_obj = 72

















[avocado]
c_in = 1
c_out = 2
classification_function = avocado_binary_classification
test_folder = ../../../Data/Real/AugNN/test_avocado_binary
img_per_obj = 72
